name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # or your preferred Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
      
    - name: Push to Target Repository
      run: |
        # Clone the repository using PAT
        git clone https://${{ secrets.GH_PAT }}@github.com/jaibeer72/jaibeer72.github.io.git repo-temp
        cd repo-temp
    
        # Check out the master branch and clean its content
        git checkout master
        git rm -rf .
        
        # Copy the new build to the repo-temp directory
        cp -r ../build/* .
    
        # Commit and push the changes
        git add .
        git commit -m "Deploy from GitHub Actions"
        git push origin master
    
        cd ..
        rm -rf repo-temp